[package]
name = "nvme"
version = "0.3.0"
edition = "2024"
repository = "https://github.com/H4n-uL/NVMe-Rust"
description = "Bare-metal NVMe driver"
license = "MIT/Apache-2.0"
keywords = ["nvme", "pcie", "no_std"]
